name: orbitdetermination
channels:
  - defaults
  - plotly
  - conda-forge
dependencies:
  - python
  - orekit
  - jupyter
  - jupyterlab
  - ipywidgets
  - numpy
  - numpy-base
  - pandas
  - nodejs # For installing Jupyter lab extensions
  - plotly
  - plotly-orca
  - psutil
